### ISSUE TITLE
[Nox.Generators] Update ETag missing error message

### ISSUE THREAD

**Issue by anna-naumova25** [NoxOrg/Nox#923]
Talk to @Mornevanzyl for more details

**Comment by Mornevanzyl** [comment]
Hi Andrii,
The thoughts were that the current error message when trying to update an entity without the ETag could be more descriptive in how to solve the issue. It should perhaps allude to supplying the ETag via the `If-Match` attribute on the HTTP Header rather than leaving the user in the dark as to how to include the ETag.

This was raised in our sprint review and suggested by @gjorgji-grgovski-authoritypartners if my memory serves me correctly.

![image](https://github.com/NoxOrg/Nox.Generator/assets/64355398/0bef2e0b-4ede-422d-a0ec-04763ee0c2a3)
