### ISSUE TITLE
[Nox.Generator] SqlException - Invalid object name 'OutboxState'

### ISSUE THREAD

**Issue by Mornevanzyl** [NoxOrg/Nox#971]
Experiencing this issue when I activate inMemory messaging in Cryptocash solution:

![image](https://github.com/NoxOrg/Nox.Generator/assets/64355398/b477810f-deed-4217-b2e0-0db9332845a5)
![image](https://github.com/NoxOrg/Nox.Generator/assets/64355398/ea04b29c-9e2b-4145-bd9d-8edaebe658f1)

**Comment by rochar** [comment]
@Mornevanzyl   I was using this scenario in CryptoCash API,  when you add messaging you need to run Migrations again and update the db because messaging is creating tables on the database to manage the Outbox


![Image](https://github.com/NoxOrg/Nox.Generator/assets/8514193/c1b2f8a8-37df-4ac5-8c79-c091854f9f26)


Actually this note is very important ⁠. See also https://masstransit.io/documentation/configuration/middleware/outbox section Entity Framework



![Image](https://github.com/NoxOrg/Nox.Generator/assets/8514193/cbe9e3d8-b82d-4d48-b1b0-e98e1c73394d)


This is a MassTransit thing, we just need to state that the database model is going to change, migrations must be executed
